package cc.aoeiuv020.panovel.server.dal.model.autogen;

import java.util.Date;

public class Novel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.id
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.requester_type
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    private String requesterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.requester_extra
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    private String requesterExtra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.update_time
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.chapters_count
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    private Integer chaptersCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.modify_time
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.id
     *
     * @return the value of novel.id
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.id
     *
     * @param id the value for novel.id
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.requester_type
     *
     * @return the value of novel.requester_type
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public String getRequesterType() {
        return requesterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.requester_type
     *
     * @param requesterType the value for novel.requester_type
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public void setRequesterType(String requesterType) {
        this.requesterType = requesterType == null ? null : requesterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.requester_extra
     *
     * @return the value of novel.requester_extra
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public String getRequesterExtra() {
        return requesterExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.requester_extra
     *
     * @param requesterExtra the value for novel.requester_extra
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public void setRequesterExtra(String requesterExtra) {
        this.requesterExtra = requesterExtra == null ? null : requesterExtra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.update_time
     *
     * @return the value of novel.update_time
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.update_time
     *
     * @param updateTime the value for novel.update_time
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.chapters_count
     *
     * @return the value of novel.chapters_count
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public Integer getChaptersCount() {
        return chaptersCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.chapters_count
     *
     * @param chaptersCount the value for novel.chapters_count
     *
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public void setChaptersCount(Integer chaptersCount) {
        this.chaptersCount = chaptersCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.modify_time
     *
     * @return the value of novel.modify_time
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.modify_time
     *
     * @param modifyTime the value for novel.modify_time
     * @mbg.generated Sat Apr 21 14:04:37 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}