name: test
env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron:  '0 20 * * fri' # 时区对cron无效，所以要提前8个小时，
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Test with Gradle
        run: |
          ./gradlew api:compileTestJava
          ./gradlew api:test --tests "**.site.*" || echo test return $?
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./api/build/reports/tests/test/
